- name: add_user_to_docker_group
  user:
    name: "{{ ansible_env.SUDO_USER }}"
    groups: docker
    append: yes

- name: restart_docker_daemon
  service:
    use: service # for WSL2 Ubuntu
    name: docker
    state: started

- name: enable_docker_daemon
  become: true
  service:
    use: service # for WSL2 Ubuntu
    name: docker
    enabled: yes